#!/bin/sh

param1=$1
param2=$2

test -z $param1 && echo "branch required." 1>&2 && exit 1

if test -z "$param2"
then
    upstream=`echo origin/master`
    branch=$param1
else
    upstream=$param1
    branch=$param2
fi

git checkout -b $branch -t $upstream
